// Codegen: derive the lazy-skills index from the real skills on disk (../.agents/skills/*/SKILL.md)
// so agent/build.ts never hand-maintains it. A remote gitRepo skill source can't be enumerated at
// runtime (the SDK can't list a GitHub subpath), so the index must be static — this makes "static"
// mean "generated from the source of truth" instead of "typed by hand and silently drifting."
//
// Run standalone (`bun run gen:skills`) or as the build.ts prelude. Emits src/lib/agent/skills.generated.ts.
import { readdirSync, existsSync, statSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url)); // web/scripts
const SKILLS_DIR = join(here, "..", "..", ".agents", "skills"); // lna/.agents/skills
const OUT = join(here, "..", "src", "lib", "agent", "skills.generated.ts"); // web/src/lib/agent/…

// SKILL.md frontmatter is the same trivial `key: value` YAML the SDK's parseSkillFrontmatter reads.
function frontmatter(md: string): Record<string, string> {
  const m = md.match(/^---\s*\n([\s\S]*?)\n---/);
  if (!m) return {};
  const out: Record<string, string> = {};
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (kv) out[kv[1]] = kv[2].trim().replace(/^["']|["']$/g, "");
  }
  return out;
}

export function genSkillsIndex(): { name: string; description: string; path: string }[] {
  const index: { name: string; description: string; path: string }[] = [];
  if (existsSync(SKILLS_DIR)) {
    for (const dir of readdirSync(SKILLS_DIR).sort()) {
      const skillMd = join(SKILLS_DIR, dir, "SKILL.md");
      if (!existsSync(skillMd) || !statSync(join(SKILLS_DIR, dir)).isDirectory()) continue;
      const fm = frontmatter(readFileSync(skillMd, "utf8"));
      index.push({ name: fm.name || dir, description: fm.description || "No description provided.", path: dir });
    }
  }
  return index;
}

export function writeSkillsIndex(): number {
  const index = genSkillsIndex();
  const body = `// GENERATED by web/gen-skills-index.ts from ../.agents/skills/*/SKILL.md — do not edit by hand.
import type { SkillIndexEntry } from "./skills-index-type";

export const SKILLS_INDEX: SkillIndexEntry[] = ${JSON.stringify(index, null, 2)};
`;
  writeFileSync(OUT, body);
  return index.length;
}

// run directly
if (import.meta.main) {
  const n = writeSkillsIndex();
  console.log(`gen-skills-index: wrote ${n} skill(s) → src/lib/agent/skills.generated.ts`);
}
