// GENERATED by web/gen-skills-index.ts from ../.agents/skills/*/SKILL.md — do not edit by hand.
import type { SkillIndexEntry } from "./skills-index-type";

export const SKILLS_INDEX: SkillIndexEntry[] = [
  {
    "name": "repo-greet",
    "description": "Prints a greeting and the sandbox host info by running its bundled script.",
    "path": "repo-greet"
  },
  {
    "name": "sum-writer",
    "description": "Compute a sum of integers and write only the total to result.txt in the workspace root.",
    "path": "sum-writer"
  }
];
